### ISSUE TITLE
Movie DB Schema

### ISSUE THREAD

**Issue by benstream** [benstream/CS372#24]
- document current movies by title, tags, misc info, and yt id or other alternative

**Comment by TechSolomon** [comment]
- [ ] YouTube Data API – https://developers.google.com/youtube/v3
- [ ] IMDb Developer – https://developer.imdb.com/ & https://imdb-api.com/
- [x] List of genres – https://en.wikipedia.org/wiki/List_of_genres & https://github.com/ishmeetkohli/imdbGenreClassification

**Comment by TechSolomon** [comment]
Draft format (tags → metadata):

```json
{
	"title": {},
	"video-id": {},
	"category": {},
	"metadata": {},
	"rating": {},
	"review": {}
}
```
